### ISSUE TITLE
Do not break webpage with javascript exceptions

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#55]
I opened a channel, then clicked the home button, and my home page was filled with a javascript exception error:

```
Cannot read properties of undefined (reading 'time')

Clear errors and retry
TypeError: Cannot read properties of undefined (reading 'time')
    at get children [as children] (http://localhost:3420/src/components/Activity.tsx:110:120)
    at http://localhost:3420/src/components/Activity.tsx:39:32
    at Object.fn (http://localhost:3420/node_modules/.vite/deps/chunk-4GRR7IEI.js?v=4e54f4ba:337:60)
    at runComputation (http://localhost:3420/node_modules/.vite/deps/chunk-D6EXEMZE.js?v=4e54f4ba:755:22)
    at updateComputation (http://localhost:3420/node_modules/.vite/deps/chunk-D6EXEMZE.js?v=4e54f4ba:738:3)
    at createRenderEffect (http://localhost:3420/node_modules/.vite/deps/chunk-D6EXEMZE.js?v=4e54f4ba:229:5)
    at insert (http://localhost:3420/node_modules/.vite/deps/chunk-4GRR7IEI.js?v=4e54f4ba:337:3)
    at http://localhost:3420/src/components/Activity.tsx:39:5
    at _$$component.location (http://localhost:3420/src/components/Activity.tsx:41:5)
    at http://localhost:3420/@solid-refresh:25:42
```

**Comment by futurepaul** [comment]
this specific error was caused by me incorrectly writing a type for onchain tx. fixed that in #56 along with an error page in case this happens elsewhere.

ideally we catch every js failure and handle in place
