### ISSUE TITLE
Reloading mutiny after a day or something causes some caching issues 

### ISSUE THREAD

**Issue by TonyGiorgio** [MutinyWallet/mutiny-web#69]
The whole app fails to load on a blank gray screen.

```
Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"index.html"}]
    at O.createHandlerBoundToURL (https://signet-app.mutinywallet.com/workbox-30e9d199.js:1:13245)
    at Object.createHandlerBoundToURL (https://signet-app.mutinywallet.com/workbox-30e9d199.js:1:14916)
    at https://signet-app.mutinywallet.com/sw.js:1:2329
    at https://signet-app.mutinywallet.com/sw.js:1:565
```

**Comment by benthecarman** [comment]
Haven't seen this anymore
